### PR TITLE
New banner for "The Big One" on behalf of @zbarmstrong

### PR DESCRIPTION
**Pull request by SteVader**
> @zbarmstrong
> Hello! We’ve got another “The Big One” tournament supporting MSF, is there space on the TCO banner? I see it rotates now!

### CODE REVIEW

**Comment by cryogen** [comment]
The other 2 end tomorrow if you want to take those out :)

**Comment by SteVader** [comment]
Two birds with one stone, I'm all for that. Done.

**Comment by cryogen** [comment]
I haven't actually tested the carousel with only one banner, did you give it a go locally?

**Comment by SteVader** [comment]
Ha ha, that crossed my mind so I checked before pushing. It works fine.

**Comment by cryogen** [comment]
Thanks! I shall merge + deploy tomorrow!

**Comment by zbarmstrong** [comment]
Hey guys, thanks so much for doing this! I'm not seeing the banner live currently; let me know if there's anything you need from me.

**Comment by SteVader** [comment]
I'm pretty sure it will only go live the next time the lobby node is restarted, is that right @cryogen?

**Pull request merged**
