### PR TITLE
Added a maybe not so glorious glory token

### PR DESCRIPTION
**Pull request by romanogit**

### CODE REVIEW

**Comment by cryogen** [comment]
Where is this token from?  Please can you attribute it if necessary

**Comment by romanogit** [comment]
It is definetly from the cloud. I just downloaded it.
https://bpng.pngfly.com/dy/15d252bc75396b2d7d3c0373b99575cd/L0KzQYm3U8I5N6Nwj5H0aYP2gLBuTfxifaNqhJ9CcnXkhLm0hB9tbF5yfdZqbD3mfLr3TfFzfF5sh95tLXLkc7zukv92dpUyTdNrY0TldLS9V8hlOmQzUaMBNkO0SIS4VcIzOmkATqQDNEK3QnB3jvc=/kisspng-laurel-wreath-gold-medal-clip-art-gold-background-5abc4bdc678d23.9166318315222896284242.png

**Comment by cryogen** [comment]
Sure, but before we use it we need to get permission.  It may be CC, do you have the original source?

**Comment by romanogit** [comment]
https://www.cleanpng.com/png-laurel-wreath-gold-medal-clip-art-gold-background-713262/

**Comment by cryogen** [comment]
Hmm, isn't amazingly clear, but hey ho!

**Pull request merged**
