### PR TITLE
Keyforge Live Banners

### PR DESCRIPTION
**Pull request by SteVader**
On behalf of @Cloggin due to #2679 build failing.

### CODE REVIEW

**Comment by SteVader** [comment]
@Cloggin - mine built, but I still can't tell you why. If I had to guess, I'd point at linting maybe? I have Prettier installed in VSCode.

**Comment by Cloggin** [comment]
@SteVader It's cause I tried to do it at all, and the universe said "bro, you promised you'd only do mobile apps, what's this web shite?"

I'm still rocking visual studio 2019, I'm sure it has to do with copy/pasting/formatting/tabsandspaces/siliconvalleyreruns.

Thanks for the assist, here.

**Comment by cryogen** [comment]
The issue was you tried to edit it without doing a 'npm install' so all the auto linting didn't happen.

However the bigger issue here is I'd like to keep it to a one banner per event if possible :)

I don't mind hosting the banners but if they start getting out of hand I might have to just start not doing them

**Comment by Cloggin** [comment]
No rule of six in the banners huh? 

*Sad face.*

Alright roll with just the first one then. Please and thanks.

**Comment by cryogen** [comment]
Sorry to be a party pooper :)

**Comment by SteVader** [comment]
I've adjusted accordingly.

**Pull request merged**
