### PR TITLE
MM: Star Alliance - Survey

### PR DESCRIPTION
**Pull request by ryanch**
Per this issue, I've implemented Survey:
https://github.com/keyteki/keyteki/issues/1172

Validation done:
* New test case passes
* Lint passes

### CODE REVIEW

**Comment by cryogen** [comment]
What happens if there's 1 card left in the deck?

**Comment by ryanch** [comment]
I added a test case for 1 card. It will prompt and force you to pick a card and discard it.

**Comment by romanogit** [comment]
After looking into slice and testing it, it seems it knows how to handle well if you have less than 2 cards.

```javascript
C:\Users\romano>node
> a = []
[]
> a.slice(0,2)
[]
> a = [1,2]
[ 1, 2 ]
> a.slice(0,2)
[ 1, 2 ]
> a = [1]
[ 1 ]
> a.slice(0,2)
[ 1 ]
> a = [1,2,3]
[ 1, 2, 3 ]
> a.slice(0,2)
[ 1, 2 ]
>                             
```

**Comment by romanogit** [comment]
I could have implemented some card with less code 😄

**Pull request merged**
