### PR TITLE
WoE: give Rampaging Brutodon its play ability

### PR DESCRIPTION
**Pull request by strib**
Not sure how I missed this before...

### CODE REVIEW

**Comment by romanogit** [comment]
I think there is another way to check for a play ability.

**Comment by strib** [comment]
> I think there is another way to check for a play ability.

I tried `isCardPlayed` but that's for cards being played I think, not play reactions.  If you find anything else, would love to change this since it's pretty clunky.

**Comment by romanogit** [comment]
Does SciOfficerMorpheus help?

**Comment by romanogit** [comment]
Look how it uses ability.properties.name:

```
event.card.abilities.reactions.some(
                        (ability) =>
                            ability.properties.name === 'Play' &&
```

**Comment by strib** [comment]
Thanks, fixed!

**Pull request merged**
