### PR TITLE
feat: implement gizelharts wrath

### PR DESCRIPTION
**Pull request by granttitus**
image

### CODE REVIEW

**Comment by cryogen** [comment]
This one has a genuine lint error, and isn't caused by the build issues

**Comment by romanogit** [comment]
I think you should not use *target* here. 

```javascript
this.play({
            effect: 'destroy each undamaged creature',
            gameAction: ability.actions.destroy(context => ({
                    target: context.game.creaturesInPlay.filter(card => !card.hasTrait('mutant'))
                }))
        });
```

**Comment by granttitus** [comment]
> I think you should not use _target_ here.
> 
> ```js
> this.play({
>             effect: 'destroy each undamaged creature',
>             gameAction: ability.actions.destroy(context => ({
>                     target: context.game.creaturesInPlay.filter(card => !card.hasTrait('mutant'))
>                 }))
>         });
> ```

Yes, you are correct. I would have caught that if I had written tests!

**Comment by granttitus** [comment]
I fixed the implementation and added tests

**Pull request merged**
