### PR TITLE
Woe side pane

### PR DESCRIPTION
**Pull request by dgbrokaw**
Adds each player's token to the side pane.

image

### CODE REVIEW

**Comment by dgbrokaw** [comment]
Might not need the new player stat

**Comment by dgbrokaw** [comment]
The img key is wrong...they'll be the same if both players have the same token.

**Comment by cryogen** [comment]
keys are only needed if the component is in an array, so you can just remove the keys entirely

**Comment by dgbrokaw** [comment]
Cool, will do.

**Pull request merged**
