### PR TITLE
WoE: implement Cursed Relic

### PR DESCRIPTION
**Pull request by strib**

### CODE REVIEW

**Comment by strib** [comment]
Hmm I surprised to see a test failure here.  I don't have a teamcity acocunt so don't know how to see what went wrong, but all tests pass on this branch for me locally.

**Comment by romanogit** [comment]
> I don't have a teamcity acocunt

Click on Login As Guest and then on Build Log

**Comment by strib** [comment]
Ah thanks.  Seems like a flake unrelated to my PR.  Rebased and trying again.

**Comment by romanogit** [comment]
We can only hope for this cursed relic to become a token 😃

**Comment by strib** [comment]
Haha yep.  We better get the token implementation done soon so this thing doesn't get stuck in our repo for too long...

**Pull request merged**
