### PR TITLE
WoE: implement the philosopher dinos

### PR DESCRIPTION
**Pull request by strib**
Issue: #2905

### CODE REVIEW

**Comment by romanogit** [comment]
@strib , you need to resolve conflict on this one

**Comment by romanogit** [comment]
Nevermind, I was able to resolve the conflict, rebuilding

**Comment by romanogit** [comment]
@strib , it has failed the build now

**Comment by strib** [comment]
@romanogit should be fixed now, the mock card didn't support `hasToken()`.

**Pull request merged**
