### PR TITLE
Add/Big-Magnet

### LINKED ISSUE #3030: (114) Big Magnet: Play: Chose a friendly creature. Take control of each upgrade in play and move it to that creature.

### PR DESCRIPTION
**Pull request by alifeee**
make Big Magnet work! :)

Part of #2903
closes #3030

#2908 says that we need another effect ("take control of each upgrade"), but I have just used "actions.attach"

### CODE REVIEW

**Comment by alifeee** [comment]
draft: will add tests for:

- Quadracorder - should switch key cost to opponent
- Disruption Field - same thing. should also move counters

**Comment by romanogit** [comment]
>  but I have just used "actions.attach"

more or less, take control of an upgrade would affect, for example, quadracorder, imho.

**Comment by alifeee** [comment]
tests added.

- Disruption Field ✅

- Quadracorder ❌

 Failing tests

- Big Magnet with Quadracorder played onto friendly creature by enemy, after big magnet played, opponent keys should cost 1 more ❌
- Big Magnet with Quadracorder played onto friendly creature by enemy, after big magnet played, friendly keys should be forgeable ❌

**Comment by alifeee** [comment]
I am not sure where to continue from here. Would appreciate some help

**Comment by romanogit** [comment]
First: Attaching an upgrade changes controller to the player attaching, which is great.

Your test for Quadracorder fails due to a very peculiar difference.
Disruption Field is attached to mindworm and you move it to Troll. 
Quadracorder is already attached to Troll and you want to change ownership.

**Comment by strib** [comment]
Nice, I checked and all the tests work if you take out the `card != context.target` clause, making it re-attach the target's upgrades to itself.

I have no clue if you're allowed to "move" an upgrade to its own parent a second time, I'll check.

**Comment by strib** [comment]
Ok, you can definitely re-attach the upgrade to the same creature and cause control to change, so removing `card !== context.target` seems correct.

But, I don't think we can fire `onCardAttached` events for cards that don't move, like for Blasters or for cards next to Dhrxgar.  So we might need a way to supress/interrupt/cancel those events.

**Comment by strib** [comment]
Ok I think https://github.com/alifeee/keyteki/pull/4 should fix it up by not firing `onCardAttached` events when the parent stays the same (but still changing the controller of the upgrade).

**Comment by alifeee** [comment]
> Your test for Quadracorder fails due to a very peculiar difference. Disruption Field is attached to mindworm and you move it to Troll. Quadracorder is already attached to Troll and you want to change ownership.

I almost feel like we should separate out that test into a different test, to check for that case.

**Comment by alifeee** [comment]
okay, I think this is done, if the tests work?

unless anyone can think of another edge case test to make

**Comment by romanogit** [comment]
Thanks @strib  and. @alifeee  - very good team work!!!!

I used your code and tests but created a MoveUpgrade action. All done in #3235

**Pull request closed without merging**
