### PR TITLE
Implemented maverick overlay

### PR DESCRIPTION
**Pull request by romanogit**
Implemented maverick overlay using merge-images library.

Added a CardImage component which is able to handle the overlay.

Added transparent images for overlaying.

### CODE REVIEW

**Comment by romanogit** [comment]
@cryogen ,
let me know if I need to do something to fix this. 

Here is `npm run lint` result:

```
C:\workspace_svn\public\keyteki>npm run lint

> keyteki@2.0.0 lint C:\workspace_svn\public\keyteki
> eslint --ext=js --ext=jsx client/ server/ test/

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .

C:\workspace_svn\public\keyteki>
```

**Comment by cryogen** [comment]
No you're good.  It's just because you need to rebase your fork against current master.  I'll merge this and it should build fine

**Comment by romanogit** [comment]
Can you explain how you did it?

**Comment by cryogen** [comment]
There's nothing for you to do, I just made some changes to the build process in the time between you creating your fork and you making the PR.

Going forwards if you sync your fork all will be well.

Btw, feel free to join us on discord https://discord.gg/EnPzhz !

**Pull request merged**
