### PR TITLE
migration to change the default value of the "order simultaneous abil…

### PR DESCRIPTION
**Pull request by dgbrokaw**
…ities" setting

### CODE REVIEW

**Comment by cryogen** [comment]
Can you update the 'base' table definition as well? The migration is only really used by me in production - the table definitions set up the clean slate version

**Comment by dgbrokaw** [comment]
I think this is what you meant.

**Comment by dgbrokaw** [comment]
I pressed the wrong button there.

**Comment by cryogen** [comment]
Yep thanks!

**Pull request merged**
