### PR TITLE
ToC: Graphical assets

### PR DESCRIPTION
**Pull request by SteVader**

### CODE REVIEW

**Comment by strib** [comment]
Note that the test failure here is fixed in #4296 , and that this PR should probably use `pack/toc` as its base branch, instead of master.

**Comment by SteVader** [comment]
Is there a sensible way for me to sort that out at this stage, or better to close this and redo?

**Comment by strib** [comment]
> Is there a sensible way for me to sort that out at this stage, or better to close this and redo?

I'm sure cryogen can sort it out, but if you want to try, you should see an edit button to the right of the PR title.  If you click it, you can change the "base:" branch from `master` to `pack/toc` (just under where you can edit the title).

**Comment by SteVader** [comment]
Awesome, cheers. Managed that on mobile, in the pub no less!

**Pull request merged**
