### PR TITLE
Woe: implement Shizyoku Swopper

### PR DESCRIPTION
**Pull request by strib**
Issue: #2902

### CODE REVIEW

**Comment by romanogit** [comment]
I am not sure if `swap` can be used to take control. I will double check.

**Comment by strib** [comment]
@romanogit hmm you are right, I don't think `swapControl` actually updates the controller.  But I don't think 2 calls to `takeControl` would be correct, since the swap has to happen all at once to avoid side effects.  What do you suggest?  Should I generalize `swap()` to also update the controllers?  Anything else that needs to be called, like `updateEffectsContexts()`?

**Comment by romanogit** [comment]
I asked a question about it in discord channel

**Comment by strib** [comment]
I'm pretty confident the existing swap rule covers it.  Just like in the same battleline, it should happen simultaneously and not trigger things like Picaroon.

**Comment by romanogit** [comment]
Took your code and changed it to takeControlOn on #3227

**Pull request closed without merging**
