### PR TITLE
Add support to ko language.

### LINKED ISSUE #1754: Is there plan to add korean language?
As release of Mass Mutation, Korea was added as new language in keyforge and lot of players are now looking forward to play in online. Is there any plans on adding Korean language in Crucible online?

I saw your awsome works on Crucible online and hope to play in korean cards too.

### PR DESCRIPTION
**Pull request by romanogit**
Fixes #1754

### CODE REVIEW

**Comment by wonkh11** [comment]
[korea.txt](https://github.com/keyteki/keyteki/files/4938690/korea.txt)

korean locale translation file

**Comment by wonkh11** [comment]
also


    {
        name: '언어',
        value: 'ko'
    }
];

should be changed

    },
    {
        name: '한국어',
        value: 'ko'
    }
];

**Comment by romanogit** [comment]
Done and pushed!

**Comment by romanogit** [comment]
@wonkh11 Thanks so much for the contribution.

The english local files were missing some entries, minor. If you want to downloaed the latest ko.json from this PR and submit the missing ones, I can merge and upload the changes

**Comment by wonkh11** [comment]
i would love to do translation! 

please upload!

**Comment by romanogit** [comment]
You can see it here:
https://raw.githubusercontent.com/keyteki/keyteki/0e0a830f089f98a307381437faadacd10328b022/public/locales/ko.json

Or you can wait for the PR to be approved and edit inline later.

**Comment by romanogit** [comment]
@wonkh11 ,
you can create a fork and edit the file directly on Github:
https://github.com/keyteki/keyteki/blob/master/public/locales/ko.json

**Comment by wonkh11** [comment]
"Mass Mutation": "집단 변이"
}
This is the minor missing one?

**Comment by wonkh11** [comment]
where do i fork from? 
your repository or keyteki

**Comment by romanogit** [comment]
You should fork from keyteki.

**Pull request merged**
